name: assignment_flutter_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0
  flutter_spinkit: ^5.2.0
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  double_back_to_close_app: ^2.1.0
  fluttertoast: ^8.2.4
  google_fonts: ^4.0.4
  hive_flutter: ^1.1.0
  page_transition: ^2.1.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
    - assets/auth/
    - assets/images/


